### ISSUE TITLE
pdfjs在线预览pdf文件报错

### ISSUE THREAD

**Issue by caochunhe** [uniquejava/blog#254]
pdfjs在线预览pdf文件报错，谷歌浏览器控制台输出报错信息为：Uncaught (in promise) Error: 无效或损坏的PDF文件 at VM1549 viewer.js:1397， 请问大神们这是什么原因造成的，怎么解决？

**Comment by uniquejava** [comment]
@caochunhe, 错误信息写得比较清楚了吧. 无效或损坏的PDF文件. 你给的文件url是什么 google 服务器能通过这个url访问到pdf吗? 是否能直接访问,还是需要cookie, session等认证信息, 访问你的文件之前是否需要登录先? 如果需要授权才能访问你的PDF、你得重新设计一下你的文件下载API (比如额外传递access_token)
